name: Python Packaging

on:
    push:
      branches:
        - enh/#7/python_packaging
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # You can specify your Python version here

      - name: Install dependencies
        run: pip install numpy pandas scikit-learn matplotlib pytest build flake8 mlflow

      - name: Install dependencies_1
        run: python -m build

      - name: Install dependencies_1
        run: pip install ./dist/housing-0.0.0-py3-none-any.whl

      - name: Upgrad mlflow
        run: pip install --upgrade mlflow

      - name: Install setuptool
        run: pip install --upgrade setuptools

      - name: create mflow experiment
        run:
          mlflow experiments create --experiment-name housing_experiment
          mkdir logs
          python /home/runner/work/mle_training/mle_training/src/housing/run_script.py


      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Python script
        run: python src/housing/run_script.py

      - name: Run mlflow ui
        run: mlflow ui

      - name: Run tests with pytest
        run: pytest
