name: SonarQube Integration

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  sonarqube-scan-backend:
    runs-on: ubuntu-latest
    name: 'SonarQube Scan Backend'
    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan1
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: doeapi
          args: >
            -Dsonar.projectKey=housing
            -Dsonar.sources=.
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
            -Dsonar.projectBaseDir=src/hosuing
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.login=${{ env.SONAR_TOKEN }}
